In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
from tensorflow.nn import relu
tf.enable_eager_execution()

In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
X = np.array(X, dtype="float32")
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [5]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
y = y.reshape(-1,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [7]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [8]:
X_train

array([[1.422e+01, 2.785e+01, 9.255e+01, ..., 8.219e-02, 1.890e-01,
        7.796e-02],
       [1.499e+01, 2.520e+01, 9.554e+01, ..., 2.899e-02, 1.565e-01,
        5.504e-02],
       [1.546e+01, 2.395e+01, 1.038e+02, ..., 2.163e-01, 3.013e-01,
        1.067e-01],
       ...,
       [1.611e+01, 1.805e+01, 1.051e+02, ..., 1.216e-01, 2.792e-01,
        8.158e-02],
       [1.180e+01, 1.726e+01, 7.526e+01, ..., 5.356e-02, 2.779e-01,
        8.121e-02],
       [1.989e+01, 2.026e+01, 1.305e+02, ..., 1.613e-01, 2.549e-01,
        9.136e-02]], dtype=float32)

In [9]:
X_test

array([[1.426e+01, 1.965e+01, 9.783e+01, ..., 1.505e-01, 2.398e-01,
        1.082e-01],
       [2.110e+01, 2.052e+01, 1.381e+02, ..., 2.280e-01, 2.268e-01,
        7.425e-02],
       [1.051e+01, 2.019e+01, 6.864e+01, ..., 6.136e-02, 2.383e-01,
        9.026e-02],
       ...,
       [1.287e+01, 1.621e+01, 8.238e+01, ..., 5.780e-02, 3.604e-01,
        7.062e-02],
       [1.086e+01, 2.148e+01, 6.851e+01, ..., 0.000e+00, 2.458e-01,
        6.592e-02],
       [1.057e+01, 1.832e+01, 6.682e+01, ..., 2.222e-02, 2.699e-01,
        6.736e-02]], dtype=float32)

In [10]:
y_train

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [11]:
y_test

array([[1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [13]:
X_train=scaler.transform(X_train)
X_train

array([[-2.7372537e-03,  1.9458790e+00, -2.0627801e-03, ...,
        -4.9147344e-01, -1.6671119e+00, -3.2320923e-01],
       [ 2.1262817e-01,  1.3394375e+00,  1.1927225e-01, ...,
        -1.3006376e+00, -2.2192056e+00, -1.6073673e+00],
       [ 3.4408513e-01,  1.0533801e+00,  4.5446569e-01, ...,
         1.5483199e+00,  2.4058384e-01,  1.2870311e+00],
       ...,
       [ 5.2588743e-01, -2.9681075e-01,  5.0721991e-01, ...,
         1.0794690e-01, -1.3483985e-01, -1.2038854e-01],
       [-6.7960048e-01, -4.7759879e-01, -7.0369631e-01, ...,
        -9.2693156e-01, -1.5692322e-01, -1.4111860e-01],
       [ 1.5831362e+00,  2.0893884e-01,  1.5379598e+00, ...,
         7.1177810e-01, -5.4763567e-01,  4.2756400e-01]], dtype=float32)

In [14]:
def sigmoid(h):
    return 1/(1+np.exp(-h))

In [15]:
initializer = tf.contrib.layers.xavier_initializer()
w=tf.Variable(initializer([30,1]), dtype="float32")
w

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.14910257],
       [-0.2794885 ],
       [ 0.07650942],
       [-0.09396797],
       [-0.2237956 ],
       [-0.07563967],
       [-0.08863252],
       [-0.2300481 ],
       [ 0.0932067 ],
       [ 0.4396339 ],
       [-0.03814259],
       [-0.12340498],
       [ 0.02246097],
       [ 0.2829486 ],
       [ 0.2754969 ],
       [ 0.03716594],
       [-0.16853598],
       [-0.10844576],
       [-0.35494453],
       [-0.0963603 ],
       [-0.05068681],
       [-0.20814587],
       [ 0.34728962],
       [-0.05851519],
       [ 0.43077582],
       [ 0.42136687],
       [ 0.2866078 ],
       [-0.14837945],
       [-0.16505101],
       [ 0.05024543]], dtype=float32)>

In [16]:
b = tf.Variable(initializer([1]), dtype="float32")
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.2212051], dtype=float32)>

In [17]:
tf.matmul(X_train,w)+b

<tf.Tensor: id=35, shape=(455, 1), dtype=float32, numpy=
array([[ 1.55203342e-02],
       [-4.55287695e-02],
       [ 1.61155605e+00],
       [ 3.72510970e-01],
       [ 7.26885855e-01],
       [-7.15110302e-01],
       [ 1.25188625e+00],
       [ 1.33115447e+00],
       [ 2.62231398e+00],
       [ 1.99731755e+00],
       [ 2.87699986e+00],
       [ 1.75351357e+00],
       [ 9.90243673e-01],
       [ 1.63298666e+00],
       [ 1.28770113e-01],
       [ 1.71493435e+00],
       [ 9.16714907e-01],
       [ 2.41586494e+00],
       [ 2.25283623e+00],
       [ 2.43483138e+00],
       [ 7.18797803e-01],
       [ 3.11160731e+00],
       [ 5.33788562e-01],
       [ 1.69403279e+00],
       [ 1.84616780e+00],
       [ 3.17032647e+00],
       [ 3.69575381e-01],
       [ 1.35157740e+00],
       [ 1.01551902e+00],
       [ 3.67715538e-01],
       [ 6.69743001e-01],
       [ 6.27295673e-01],
       [ 4.21984196e-02],
       [-6.32479429e-01],
       [ 1.46050024e+00],
       [ 1.71440148e+00],
       

In [18]:
hypothesis = tf.sigmoid(tf.matmul(X_train,w)+b)
hypothesis

<tf.Tensor: id=41, shape=(455, 1), dtype=float32, numpy=
array([[0.50388   ],
       [0.48861977],
       [0.83362734],
       [0.5920656 ],
       [0.6741215 ],
       [0.32847065],
       [0.77762616],
       [0.79103154],
       [0.9322839 ],
       [0.8805152 ],
       [0.9466976 ],
       [0.8523954 ],
       [0.729136  ],
       [0.83657837],
       [0.5321481 ],
       [0.84747523],
       [0.7143723 ],
       [0.9180291 ],
       [0.90489495],
       [0.91944516],
       [0.6723422 ],
       [0.95736897],
       [0.6303663 ],
       [0.84475374],
       [0.86367655],
       [0.9597022 ],
       [0.5913564 ],
       [0.7943874 ],
       [0.7340988 ],
       [0.59090686],
       [0.6614456 ],
       [0.651876  ],
       [0.51054806],
       [0.34694856],
       [0.8116092 ],
       [0.8474063 ],
       [0.7937006 ],
       [0.95170873],
       [0.5122809 ],
       [0.7504566 ],
       [0.739262  ],
       [0.47497794],
       [0.8985004 ],
       [0.54399395],
       [0.30946726]

In [19]:
optimizer = tf.train.AdamOptimizer(0.001)

In [20]:
for step in range(100):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X_train,w)+b)
        cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1-y_train) * tf.log(1-hypothesis))
        grads=tape.gradient(cost, [w,b])
        optimizer.apply_gradients(grads_and_vars=zip(grads,[w,b]))
    
    if step % 10 == 0:
        print("="*50)
        print("step: {}, cost: {}, w:{}, b:{}".format(step, cost.numpy(), w.numpy(), b.numpy()))
        print("="*50)

step: 0, cost: 0.8089044094085693, w:[[-0.15010257]
 [-0.2804885 ]
 [ 0.07550941]
 [-0.09496798]
 [-0.2247956 ]
 [-0.07663967]
 [-0.08963253]
 [-0.2310481 ]
 [ 0.0922067 ]
 [ 0.43863392]
 [-0.03914259]
 [-0.12240499]
 [ 0.02146097]
 [ 0.28194863]
 [ 0.274497  ]
 [ 0.03616594]
 [-0.16953598]
 [-0.10944577]
 [-0.35394454]
 [-0.09736029]
 [-0.0516868 ]
 [-0.20914587]
 [ 0.34628963]
 [-0.05951519]
 [ 0.42977583]
 [ 0.42036688]
 [ 0.2856078 ]
 [-0.14937945]
 [-0.16605102]
 [ 0.04924544]], b:[1.2202051]
step: 10, cost: 0.7376596331596375, w:[[-0.16006926]
 [-0.29044935]
 [ 0.06554291]
 [-0.10493299]
 [-0.23476538]
 [-0.08660614]
 [-0.09959812]
 [-0.24101505]
 [ 0.08224398]
 [ 0.42867246]
 [-0.04910459]
 [-0.1123946 ]
 [ 0.01150041]
 [ 0.2719872 ]
 [ 0.267669  ]
 [ 0.02621919]
 [-0.17947823]
 [-0.11939842]
 [-0.34392145]
 [-0.1072797 ]
 [-0.06165626]
 [-0.21911658]
 [ 0.33632052]
 [-0.06948327]
 [ 0.419798  ]
 [ 0.41039377]
 [ 0.27563694]
 [-0.15935053]
 [-0.17602453]
 [ 0.03926836]], b:[1.21

In [21]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.1282964], dtype=float32)>

In [22]:
X_test = scaler.transform(X_test)
X_test

array([[ 0.00845056,  0.06934272,  0.21220118, ...,  0.54751164,
        -0.8041469 ,  1.3710725 ],
       [ 1.921568  ,  0.26843882,  1.8463703 , ...,  1.7262752 ,
        -1.0249846 , -0.5310726 ],
       [-1.0404078 ,  0.19291969, -0.9723381 , ..., -0.80829465,
        -0.82962835,  0.36593315],
       ...,
       [-0.38032636, -0.71788716, -0.41476473, ..., -0.8624418 ,
         1.2445449 , -0.7344535 ],
       [-0.9425145 ,  0.4881306 , -0.9776134 , ..., -1.7415713 ,
        -0.702222  , -0.9977842 ],
       [-1.0236262 , -0.23502226, -1.0461942 , ..., -1.4036083 ,
        -0.29282346, -0.91710436]], dtype=float32)

In [23]:
predict=tf.sigmoid(tf.matmul(X_test,w)+b)
predict

<tf.Tensor: id=6440, shape=(114, 1), dtype=float32, numpy=
array([[0.27151066],
       [0.29681018],
       [0.9041547 ],
       [0.5962521 ],
       [0.89236593],
       [0.5573883 ],
       [0.26526064],
       [0.81507295],
       [0.71150684],
       [0.86641157],
       [0.79460156],
       [0.05827931],
       [0.52878356],
       [0.6423918 ],
       [0.9032293 ],
       [0.9215115 ],
       [0.58825135],
       [0.81918234],
       [0.9542322 ],
       [0.47172725],
       [0.9271624 ],
       [0.78460157],
       [0.94349104],
       [0.01738524],
       [0.03478342],
       [0.5904002 ],
       [0.3301826 ],
       [0.93064964],
       [0.84147894],
       [0.28171116],
       [0.8756112 ],
       [0.72738206],
       [0.62620664],
       [0.8142401 ],
       [0.99175227],
       [0.84479797],
       [0.914288  ],
       [0.779802  ],
       [0.4231736 ],
       [0.8158535 ],
       [0.30255324],
       [0.15896192],
       [0.9005312 ],
       [0.8949384 ],
       [0.6365912

In [24]:
predict01 = tf.cast(predict > 0.5, dtype=tf.float32)
print("================")
print("predict01")
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(114, 1), dtype=float32)


In [25]:
ac01=tf.equal(predict01, y_test)
ac01

<tf.Tensor: id=6445, shape=(114, 1), dtype=bool, numpy=
array([[False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],


In [26]:
ac02=tf.cast(ac01, dtype="float32")
ac02

<tf.Tensor: id=6446, shape=(114, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
     

In [27]:
ac03=tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=6448, shape=(), dtype=float32, numpy=0.8245614>

In [28]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y_test), dtype=tf.float32))
print("=======================")
print("accuracy")
print(accuracy.numpy())

accuracy
0.8245614
