In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3], dtype="float32")
y=np.array([2, 2.5, 3.5], dtype="float32")

In [3]:
x

array([1., 2., 3.], dtype=float32)

In [4]:
y

array([2. , 2.5, 3.5], dtype=float32)

In [5]:
w = 2
b = 1

In [6]:
hypothesis = x*w + b
hypothesis

array([3., 5., 7.], dtype=float32)

In [7]:
w_gred = 1/3 *np.dot((hypothesis-y), x.T)
w_gred

5.5

In [8]:
w = w - w_gred
w

-3.5

In [9]:
b_gred= 1/3 * np.sum(hypothesis-y)
b_gred

2.333333333333333

In [10]:
b = b - b_gred
b

-1.333333333333333

In [11]:
for i in range(100):
    hypothesis = x*w + b
    MSE = np.sum((hypothesis-y)**2)
    print("MSE:", MSE)
    w_gred = 1/3*np.dot((hypothesis-y), x.T)
    print("w_gred: ", w_gred)
    b_gred = 1/3 * np.sum(hypothesis-y)
    print("b_gred:", b_gred)
    w=w-w_gred
    print("w:",w)
    b=b-b_gred
    print("b:", b)

MSE: 399.16666
w_gred:  -24.833333333333332
b_gred: -11.0
w: 21.333333333333332
b: 9.666666666666668
MSE: 8247.723
w_gred:  113.05556233723958
b_gred: 49.666666666666664
w: -91.72222900390625
b: -40.0
MSE: 170481.0
w_gred:  -513.8704020182291
b_gred: -226.11112467447916
w: 422.1481730143229
b: 186.11112467447916
MSE: 3523906.0
w_gred:  2336.41357421875
b_gred: 1027.74072265625
w: -1914.2654012044272
b: -841.6295979817709
MSE: 72840500.0
w_gred:  -10622.330078125
b_gred: -4672.826822916666
w: 8708.064676920572
b: 3831.197224934895
MSE: 1505641300.0
w_gred:  48294.197916666664
b_gred: 21244.658854166664
w: -39586.133239746094
b: -17413.46162923177
MSE: 31122194000.0
w_gred:  -219568.04166666666
b_gred: -96588.39583333333
w: 179981.90842692056
b: 79174.93420410156
MSE: 643308000000.0
w_gred:  998259.6666666666
b_gred: 439136.0833333333
w: -818277.7582397461
b: -359961.14912923175
MSE: 13297428000000.0
w_gred:  -4538557.666666666
b_gred: -1996519.3333333333
w: 3720279.90842692
b: 1636558.1

C:\Users\user\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in square
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':
