In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


In [2]:
tf.enable_eager_execution()
tf.__version__

'1.15.0'

In [3]:
X = np.array([2, 4, 6, 8], dtype="float32")
Y = np.array([81, 93, 91, 97], dtype="float32")

In [4]:
W = tf.Variable([2], dtype="float32")
b = tf.Variable([1], dtype="float32")

In [5]:
W

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.], dtype=float32)>

In [6]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>

In [7]:
learning_rate = 0.01

In [8]:
for i in range(1000):
    with tf.GradientTape() as tape:
        hypothesis = W * X + b
        print("hypothesis:", hypothesis)
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
        print("cost", cost)
        W_grad, b_grad = tape.gradient(cost, [W, b])
        print("W_grad:", W_grad, ":b_grad:", b_grad)
        W.assign_sub(W_grad*learning_rate)
        b.assign_sub(b_grad*learning_rate)

hypothesis: tf.Tensor([ 5.  9. 13. 17.], shape=(4,), dtype=float32)
cost tf.Tensor(6329.0, shape=(), dtype=float32)
W_grad: tf.Tensor([-798.], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-159.], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([22.55     42.51     62.469997 82.42999 ], shape=(4,), dtype=float32)
cost tf.Tensor(1747.9723, shape=(), dtype=float32)
W_grad: tf.Tensor([-303.30005], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-76.020004], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 29.376202  55.402203  81.4282   107.4542  ], shape=(4,), dtype=float32)
cost tf.Tensor(1069.8801, shape=(), dtype=float32)
W_grad: tf.Tensor([-113.717995], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-44.169598], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 32.09226  60.39262  88.69298 116.99334], shape=(4,), dtype=float32)
cost tf.Tensor(965.0661, shape=(), dtype=float32)
W_grad: tf.Tensor([-41.07021], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-31.914402], shape=(1,), d

cost tf.Tensor(752.1078, shape=(), dtype=float32)
W_grad: tf.Tensor([3.6298141], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-21.661568], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 39.33194  66.24688  93.16182 120.07675], shape=(4,), dtype=float32)
cost tf.Tensor(747.2916, shape=(), dtype=float32)
W_grad: tf.Tensor([3.618164], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-21.591305], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 39.47549  66.31806  93.16064 120.00321], shape=(4,), dtype=float32)
cost tf.Tensor(742.5067, shape=(), dtype=float32)
W_grad: tf.Tensor([3.6063728], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-21.5213], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 39.618576  66.38902   93.15946  119.92991 ], shape=(4,), dtype=float32)
cost tf.Tensor(737.75256, shape=(), dtype=float32)
W_grad: tf.Tensor([3.5946426], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-21.451515], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 39.761196  66.45975   93.1

hypothesis: tf.Tensor([ 44.472015  68.795906  93.1198   117.443695], shape=(4,), dtype=float32)
cost tf.Tensor(585.6425, shape=(), dtype=float32)
W_grad: tf.Tensor([3.197998], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-19.084293], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 44.5989   68.85883  93.11877 117.3787 ], shape=(4,), dtype=float32)
cost tf.Tensor(581.9042, shape=(), dtype=float32)
W_grad: tf.Tensor([3.1876678], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-19.0224], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 44.72537  68.92155  93.11773 117.31391], shape=(4,), dtype=float32)
cost tf.Tensor(578.1901, shape=(), dtype=float32)
W_grad: tf.Tensor([3.1772957], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-18.960722], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 44.851433  68.98407   93.1167   117.24934 ], shape=(4,), dtype=float32)
cost tf.Tensor(574.5, shape=(), dtype=float32)
W_grad: tf.Tensor([3.167015], shape=(1,), dtype=float32) :b_grad: tf.Tensor(

hypothesis: tf.Tensor([ 49.461685  71.270355  93.07902  114.88769 ], shape=(4,), dtype=float32)
cost tf.Tensor(447.78363, shape=(), dtype=float32)
W_grad: tf.Tensor([2.7901993], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-16.650627], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 49.572388  71.32526   93.07811  114.83098 ], shape=(4,), dtype=float32)
cost tf.Tensor(444.93793, shape=(), dtype=float32)
W_grad: tf.Tensor([2.7811432], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-16.596634], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 49.68273   71.379974  93.07722  114.77446 ], shape=(4,), dtype=float32)
cost tf.Tensor(442.11078, shape=(), dtype=float32)
W_grad: tf.Tensor([2.772171], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-16.542809], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 49.792717  71.43452   93.07632  114.71812 ], shape=(4,), dtype=float32)
cost tf.Tensor(439.30182, shape=(), dtype=float32)
W_grad: tf.Tensor([2.7631683], shape=(1,), dtype=float32) :

hypothesis: tf.Tensor([ 53.815056  73.429245  93.043434 112.65762 ], shape=(4,), dtype=float32)
cost tf.Tensor(342.8431, shape=(), dtype=float32)
W_grad: tf.Tensor([2.4343414], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-14.527321], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 53.91164  73.47714  93.04265 112.60815], shape=(4,), dtype=float32)
cost tf.Tensor(340.67697, shape=(), dtype=float32)
W_grad: tf.Tensor([2.4264565], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-14.480211], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 54.00791   73.52489   93.041855 112.55884 ], shape=(4,), dtype=float32)
cost tf.Tensor(338.52487, shape=(), dtype=float32)
W_grad: tf.Tensor([2.418602], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-14.433254], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 54.103874  73.57248   93.04108  112.509674], shape=(4,), dtype=float32)
cost tf.Tensor(336.38654, shape=(), dtype=float32)
W_grad: tf.Tensor([2.410759], shape=(1,), dtype=float32) :b_grad

W_grad: tf.Tensor([2.1516647], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-12.840519], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 57.358833  75.18665   93.01447  110.84229 ], shape=(4,), dtype=float32)
cost tf.Tensor(267.97183, shape=(), dtype=float32)
W_grad: tf.Tensor([2.1447296], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-12.798874], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 57.443924  75.22885   93.01378  110.798706], shape=(4,), dtype=float32)
cost tf.Tensor(266.29053, shape=(), dtype=float32)
W_grad: tf.Tensor([2.1377869], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-12.75737], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 57.528748  75.27092   93.013084 110.75526 ], shape=(4,), dtype=float32)
cost tf.Tensor(264.6199, shape=(), dtype=float32)
W_grad: tf.Tensor([2.130867], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-12.715996], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 57.61329   75.312836  93.01239  110.711945], shape=(4,), dtype=flo

W_grad: tf.Tensor([1.889534], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-11.276089], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 60.555935  76.77214   92.98834  109.20455 ], shape=(4,), dtype=float32)
cost tf.Tensor(208.55194, shape=(), dtype=float32)
W_grad: tf.Tensor([1.8834496], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-11.239515], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 60.63066   76.809204  92.98774  109.166275], shape=(4,), dtype=float32)
cost tf.Tensor(207.25531, shape=(), dtype=float32)
W_grad: tf.Tensor([1.877388], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-11.20306], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 60.705147  76.84613   92.98712  109.12811 ], shape=(4,), dtype=float32)
cost tf.Tensor(205.96709, shape=(), dtype=float32)
W_grad: tf.Tensor([1.8712234], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-11.166744], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 60.77939  76.88295  92.98652 109.09009], shape=(4,), dtype=float32

hypothesis: tf.Tensor([ 63.363525  78.16446   92.96539  107.76633 ], shape=(4,), dtype=float32)
cost tf.Tensor(162.72876, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6539307], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-9.870148], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 63.429146  78.19701   92.96486  107.73272 ], shape=(4,), dtype=float32)
cost tf.Tensor(161.72887, shape=(), dtype=float32)
W_grad: tf.Tensor([1.648613], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-9.838135], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 63.494556  78.22944   92.964325 107.69921 ], shape=(4,), dtype=float32)
cost tf.Tensor(160.73544, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6432533], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-9.806234], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 63.55975  78.26177  92.96379 107.66581], shape=(4,), dtype=float32)
cost tf.Tensor(159.74841, shape=(), dtype=float32)
W_grad: tf.Tensor([1.6379051], shape=(1,), dtype=float32) :b_grad:

hypothesis: tf.Tensor([ 65.94413   79.444214  92.944305 106.4444  ], shape=(4,), dtype=float32)
cost tf.Tensor(125.85388, shape=(), dtype=float32)
W_grad: tf.Tensor([1.4430618], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-8.611477], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 66.00138  79.47261  92.94383 106.41506], shape=(4,), dtype=float32)
cost tf.Tensor(125.09268, shape=(), dtype=float32)
W_grad: tf.Tensor([1.4383469], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-8.583557], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 66.05845   79.50091   92.943375 106.38583 ], shape=(4,), dtype=float32)
cost tf.Tensor(124.3365, shape=(), dtype=float32)
W_grad: tf.Tensor([1.4337234], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-8.555717], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 66.115326  79.52911   92.9429   106.35669 ], shape=(4,), dtype=float32)
cost tf.Tensor(123.585205, shape=(), dtype=float32)
W_grad: tf.Tensor([1.4290161], shape=(1,), dtype=float32) :b_grad

W_grad: tf.Tensor([1.2754898], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-7.61158], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 68.0448   80.48596  92.92713 105.3683 ], shape=(4,), dtype=float32)
cost tf.Tensor(99.545166, shape=(), dtype=float32)
W_grad: tf.Tensor([1.2713242], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-7.5869026], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 68.095245  80.51099   92.92673  105.34247 ], shape=(4,), dtype=float32)
cost tf.Tensor(98.9543, shape=(), dtype=float32)
W_grad: tf.Tensor([1.267273], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-7.5622864], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 68.145515  80.53591   92.92631  105.3167  ], shape=(4,), dtype=float32)
cost tf.Tensor(98.36737, shape=(), dtype=float32)
W_grad: tf.Tensor([1.2630768], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-7.537781], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 68.19563  80.56077  92.9259  105.29103], shape=(4,), dtype=float32)
cost t

hypothesis: tf.Tensor([ 69.761345  81.33722   92.9131   104.48898 ], shape=(4,), dtype=float32)
cost tf.Tensor(80.51816, shape=(), dtype=float32)
W_grad: tf.Tensor([1.1310196], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-6.7496758], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 69.80622   81.35948   92.912735 104.466   ], shape=(4,), dtype=float32)
cost tf.Tensor(80.05053, shape=(), dtype=float32)
W_grad: tf.Tensor([1.1274033], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-6.7277794], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 69.85095   81.38166   92.91237  104.443085], shape=(4,), dtype=float32)
cost tf.Tensor(79.58594, shape=(), dtype=float32)
W_grad: tf.Tensor([1.1237183], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-6.705967], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 69.89553  81.40377  92.912   104.42024], shape=(4,), dtype=float32)
cost tf.Tensor(79.12438, shape=(), dtype=float32)
W_grad: tf.Tensor([1.1200485], shape=(1,), dtype=float32) :b_grad: 

hypothesis: tf.Tensor([ 71.36817  82.13407  92.89997 103.66587], shape=(4,), dtype=float32)
cost tf.Tensor(64.721054, shape=(), dtype=float32)
W_grad: tf.Tensor([0.9997101], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.9659576], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 71.40784  82.15374  92.89964 103.64555], shape=(4,), dtype=float32)
cost tf.Tensor(64.35574, shape=(), dtype=float32)
W_grad: tf.Tensor([0.99645996], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.9466133], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 71.44737   82.173355  92.89933  103.625305], shape=(4,), dtype=float32)
cost tf.Tensor(63.99276, shape=(), dtype=float32)
W_grad: tf.Tensor([0.99329376], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.9273186], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 71.48678   82.192894  92.899    103.60512 ], shape=(4,), dtype=float32)
cost tf.Tensor(63.63218, shape=(), dtype=float32)
W_grad: tf.Tensor([0.99004364], shape=(1,), dtype=float32) :b_grad:

W_grad: tf.Tensor([0.8836441], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.2732315], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 72.8235    82.85579   92.88808  102.920364], shape=(4,), dtype=float32)
cost tf.Tensor(52.093918, shape=(), dtype=float32)
W_grad: tf.Tensor([0.8807678], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.256134], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 72.85845   82.87312   92.887794 102.902466], shape=(4,), dtype=float32)
cost tf.Tensor(51.810326, shape=(), dtype=float32)
W_grad: tf.Tensor([0.87794495], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.2390823], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 72.89328   82.890396  92.88751  102.88462 ], shape=(4,), dtype=float32)
cost tf.Tensor(51.528618, shape=(), dtype=float32)
W_grad: tf.Tensor([0.87509155], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-5.2220955], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 72.928    82.90761  92.88722 102.86684], shape=(4,), dtype=flo

W_grad: tf.Tensor([0.77095795], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.6007843], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 74.19773   83.537285  92.87685  102.2164  ], shape=(4,), dtype=float32)
cost tf.Tensor(41.636806, shape=(), dtype=float32)
W_grad: tf.Tensor([0.76844025], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.585869], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 74.22822   83.552414  92.8766   102.20079 ], shape=(4,), dtype=float32)
cost tf.Tensor(41.42094, shape=(), dtype=float32)
W_grad: tf.Tensor([0.7660141], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.5709877], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 74.258606  83.567474  92.87635  102.18522 ], shape=(4,), dtype=float32)
cost tf.Tensor(41.20653, shape=(), dtype=float32)
W_grad: tf.Tensor([0.76348114], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.556175], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 74.2889    83.582504  92.8761   102.16971 ], shape=(4,), dtype=f

W_grad: tf.Tensor([0.6858597], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.0930862], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 75.23528   84.05182   92.86836  101.684906], shape=(4,), dtype=float32)
cost tf.Tensor(34.68526, shape=(), dtype=float32)
W_grad: tf.Tensor([0.6836319], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.079815], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 75.262405  84.06527   92.86814  101.671005], shape=(4,), dtype=float32)
cost tf.Tensor(34.514412, shape=(), dtype=float32)
W_grad: tf.Tensor([0.68138885], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.0665894], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 75.28944   84.07868   92.86792  101.657166], shape=(4,), dtype=float32)
cost tf.Tensor(34.34469, shape=(), dtype=float32)
W_grad: tf.Tensor([0.6792221], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-4.053398], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 75.31639  84.09205  92.86771 101.64336], shape=(4,), dtype=float32

cost tf.Tensor(28.913727, shape=(), dtype=float32)
W_grad: tf.Tensor([0.6042557], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-3.606102], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 76.2305    84.545364  92.86024  101.17511 ], shape=(4,), dtype=float32)
cost tf.Tensor(28.780256, shape=(), dtype=float32)
W_grad: tf.Tensor([0.60237885], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-3.5943947], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 76.254395  84.55721   92.86003  101.16286 ], shape=(4,), dtype=float32)
cost tf.Tensor(28.647629, shape=(), dtype=float32)
W_grad: tf.Tensor([0.6003418], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-3.5827522], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 76.27821  84.56903  92.85984 101.15066], shape=(4,), dtype=float32)
cost tf.Tensor(28.51587, shape=(), dtype=float32)
W_grad: tf.Tensor([0.5984268], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-3.5711288], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 76.301956  84.580

W_grad: tf.Tensor([0.4814453], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.8727264], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 77.72921   85.2886    92.847984 100.40737 ], shape=(4,), dtype=float32)
cost tf.Tensor(21.297258, shape=(), dtype=float32)
W_grad: tf.Tensor([0.47984314], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.8634186], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 77.748245  85.298035  92.847824 100.39761 ], shape=(4,), dtype=float32)
cost tf.Tensor(21.213102, shape=(), dtype=float32)
W_grad: tf.Tensor([0.47824097], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.8541412], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 77.76722  85.30745  92.84767 100.38789], shape=(4,), dtype=float32)
cost tf.Tensor(21.12948, shape=(), dtype=float32)
W_grad: tf.Tensor([0.47670746], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.844883], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 77.78614   85.316826  92.84752  100.37821 ], shape=(4,), dtype=flo

hypothesis: tf.Tensor([ 78.37708   85.609886  92.84269  100.07549 ], shape=(4,), dtype=float32)
cost tf.Tensor(18.586908, shape=(), dtype=float32)
W_grad: tf.Tensor([0.42689514], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.5474243], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 78.39402   85.618286  92.84255  100.06682 ], shape=(4,), dtype=float32)
cost tf.Tensor(18.520302, shape=(), dtype=float32)
W_grad: tf.Tensor([0.42552185], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.5391617], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 78.4109    85.626656  92.84241  100.05817 ], shape=(4,), dtype=float32)
cost tf.Tensor(18.454128, shape=(), dtype=float32)
W_grad: tf.Tensor([0.42409515], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.5309372], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([ 78.42773   85.634995  92.84227  100.049545], shape=(4,), dtype=float32)
cost tf.Tensor(18.388393, shape=(), dtype=float32)
W_grad: tf.Tensor([0.4227066], shape=(1,), dtype=float3

cost tf.Tensor(16.441746, shape=(), dtype=float32)
W_grad: tf.Tensor([0.37979126], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.2663002], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([78.96852  85.90318  92.837845 99.772514], shape=(4,), dtype=float32)
cost tf.Tensor(16.389057, shape=(), dtype=float32)
W_grad: tf.Tensor([0.378479], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.2589684], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([78.98354  85.91064  92.83773  99.764824], shape=(4,), dtype=float32)
cost tf.Tensor(16.336668, shape=(), dtype=float32)
W_grad: tf.Tensor([0.37730408], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.2516327], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([78.99851 85.91806 92.83761 99.75716], shape=(4,), dtype=float32)
cost tf.Tensor(16.284634, shape=(), dtype=float32)
W_grad: tf.Tensor([0.37608337], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.2443314], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.013435 85.92546  92.8374

hypothesis: tf.Tensor([79.466225 86.15     92.833786 99.51756 ], shape=(4,), dtype=float32)
cost tf.Tensor(14.743959, shape=(), dtype=float32)
W_grad: tf.Tensor([0.33783722], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.0162125], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.47963  86.156654 92.83368  99.510704], shape=(4,), dtype=float32)
cost tf.Tensor(14.7022295, shape=(), dtype=float32)
W_grad: tf.Tensor([0.336792], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.0096664], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.49299 86.16328 92.83357 99.50386], shape=(4,), dtype=float32)
cost tf.Tensor(14.660794, shape=(), dtype=float32)
W_grad: tf.Tensor([0.335701], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-2.003151], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.50631  86.16988  92.833466 99.49704 ], shape=(4,), dtype=float32)
cost tf.Tensor(14.619601, shape=(), dtype=float32)
W_grad: tf.Tensor([0.33463287], shape=(1,), dtype=float32) :b_grad: tf.Tensor([

cost tf.Tensor(13.30177, shape=(), dtype=float32)
W_grad: tf.Tensor([0.2976532], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.7763214], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.96987  86.399765 92.829666 99.25957 ], shape=(4,), dtype=float32)
cost tf.Tensor(13.269398, shape=(), dtype=float32)
W_grad: tf.Tensor([0.296669], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.770565], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.98164  86.40561  92.829575 99.25354 ], shape=(4,), dtype=float32)
cost tf.Tensor(13.237206, shape=(), dtype=float32)
W_grad: tf.Tensor([0.29574585], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.7648163], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([79.99338 86.41143 92.82948 99.24753], shape=(4,), dtype=float32)
cost tf.Tensor(13.205233, shape=(), dtype=float32)
W_grad: tf.Tensor([0.2947998], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.7590904], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.00507  86.41723  92.829384 9

hypothesis: tf.Tensor([80.38095  86.60363  92.82631  99.048996], shape=(4,), dtype=float32)
cost tf.Tensor(12.20764, shape=(), dtype=float32)
W_grad: tf.Tensor([0.26312256], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.5700569], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.39139  86.60881  92.826225 99.04364 ], shape=(4,), dtype=float32)
cost tf.Tensor(12.18232, shape=(), dtype=float32)
W_grad: tf.Tensor([0.26224518], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.5649681], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.401794 86.61397  92.82614  99.038315], shape=(4,), dtype=float32)
cost tf.Tensor(12.157194, shape=(), dtype=float32)
W_grad: tf.Tensor([0.26141357], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.5598907], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.41217  86.61911  92.82606  99.033005], shape=(4,), dtype=float32)
cost tf.Tensor(12.132223, shape=(), dtype=float32)
W_grad: tf.Tensor([0.26058197], shape=(1,), dtype=float32) :b_grad: tf.Te

cost tf.Tensor(11.293935, shape=(), dtype=float32)
W_grad: tf.Tensor([0.23028564], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.3742981], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.79145  86.807205 92.82295  98.8387  ], shape=(4,), dtype=float32)
cost tf.Tensor(11.274542, shape=(), dtype=float32)
W_grad: tf.Tensor([0.22951508], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.3698463], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.80056  86.811714 92.822876 98.83403 ], shape=(4,), dtype=float32)
cost tf.Tensor(11.2553, shape=(), dtype=float32)
W_grad: tf.Tensor([0.22873688], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.3654099], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.80964 86.81622 92.82281 98.82939], shape=(4,), dtype=float32)
cost tf.Tensor(11.236158, shape=(), dtype=float32)
W_grad: tf.Tensor([0.22807312], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.3609695], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([80.81869 86.82071 92.82273 

W_grad: tf.Tensor([0.20220947], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.2068634], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.13364 86.9769  92.82016 98.66342], shape=(4,), dtype=float32)
cost tf.Tensor(10.593892, shape=(), dtype=float32)
W_grad: tf.Tensor([0.20159912], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.2029419], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.14164  86.980865 92.8201   98.659325], shape=(4,), dtype=float32)
cost tf.Tensor(10.57904, shape=(), dtype=float32)
W_grad: tf.Tensor([0.20096588], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.1990356], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.14961 86.98482 92.82003 98.65524], shape=(4,), dtype=float32)
cost tf.Tensor(10.564285, shape=(), dtype=float32)
W_grad: tf.Tensor([0.20030975], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.1951485], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.15756 86.98876 92.81997 98.65117], shape=(4,), dtype=float32)
cost tf.Tensor(1

hypothesis: tf.Tensor([81.42707  87.12242  92.817764 98.51311 ], shape=(4,), dtype=float32)
cost tf.Tensor(10.080521, shape=(), dtype=float32)
W_grad: tf.Tensor([0.1776352], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.0598183], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.43412 87.12591 92.8177  98.50949], shape=(4,), dtype=float32)
cost tf.Tensor(10.069007, shape=(), dtype=float32)
W_grad: tf.Tensor([0.17700958], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.0563889], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.44115  87.129395 92.81765  98.5059  ], shape=(4,), dtype=float32)
cost tf.Tensor(10.057549, shape=(), dtype=float32)
W_grad: tf.Tensor([0.17647552], shape=(1,), dtype=float32) :b_grad: tf.Tensor([-1.0529556], shape=(1,), dtype=float32)
hypothesis: tf.Tensor([81.44814  87.132866 92.81759  98.50231 ], shape=(4,), dtype=float32)
cost tf.Tensor(10.046165, shape=(), dtype=float32)
W_grad: tf.Tensor([0.17588806], shape=(1,), dtype=float32) :b_grad: tf.Tenso

In [11]:
W[0]

<tf.Tensor: id=39034, shape=(), dtype=float32, numpy=2.7936075>

In [12]:
b[0]

<tf.Tensor: id=39039, shape=(), dtype=float32, numpy=76.05436>